# Generated by Django 5.2.17 on 2026-09-11 19:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Ex: ZAKIR, PRESIDENT, TRESORIER, SECRETAIRE_GENERAL, COMMUNICATION', max_length=50, unique=True, verbose_name='Code unique')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la fonction')),
                ('category', models.CharField(choices=[('SPIRITUAL', 'Charge Spirituelle & Cultuelle (ex: Zakir)'), ('EXECUTIVE', 'Bureau Exécutif (Présidence, Secrétariat, Trésorerie)'), ('COMMISSION', 'Commission Spécialisée (Communication, Organisation, Social)'), ('COMMUNITY', 'Membres & Collèges')], default='COMMUNITY', max_length=30, verbose_name='Catégorie de rôle')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description de la charge')),
                ('rank', models.PositiveSmallIntegerField(default=100, help_text='Pour l’ordre d’affichage dans l’organigramme (les plus petits en premier)', verbose_name='Rang protocolaire')),
            ],
            options={
                'verbose_name': 'Fonction / Rôle Dahirah',
                'verbose_name_plural': 'Fonctions / Rôles Dahirah',
                'ordering': ['rank', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MemberRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date de début de fonction')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin de fonction')),
                ('is_current', models.BooleanField(default=True, verbose_name='Fonction actuelle')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observations / Décret / Mandat')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dairah_roles', to='members.member', verbose_name='Membre')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='roles.role', verbose_name='Fonction / Rôle')),
            ],
            options={
                'verbose_name': 'Attribution de fonction Dahirah',
                'verbose_name_plural': 'Attributions de fonctions Dahirah',
                'ordering': ['-is_current', 'role__rank', '-start_date'],
                'indexes': [models.Index(fields=['is_current', 'role'], name='idx_mrole_current_role')],
            },
        ),
    ]
