# Generated by Django 5.2.17 on 2026-09-11 19:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre d’affichage')),
            ],
            options={
                'verbose_name': 'Catégorie de profession',
                'verbose_name_plural': 'Catégories de professions',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Intitulé du métier')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professions', to='professions.professioncategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Profession / Métier',
                'verbose_name_plural': 'Professions / Métiers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MemberProfession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Ex: Développeur Full-Stack, Directrice de publication, Gérant', max_length=150, verbose_name='Intitulé libre du poste / activité')),
                ('organization', models.CharField(blank=True, help_text='Nom de l’entreprise ou Indépendant', max_length=150, null=True, verbose_name='Structure / Entreprise')),
                ('is_primary', models.BooleanField(default=True, verbose_name='Profession principale')),
                ('is_current', models.BooleanField(default=True, verbose_name='En cours')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professions', to='members.member', verbose_name='Membre')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_professions', to='professions.profession', verbose_name='Profession référencée')),
            ],
            options={
                'verbose_name': 'Profession exercée par le membre',
                'verbose_name_plural': 'Professions exercées par les membres',
                'ordering': ['-is_primary', '-is_current'],
                'constraints': [models.UniqueConstraint(fields=('member', 'profession', 'is_current'), name='unique_current_member_profession')],
            },
        ),
    ]
