# Generated by Django 5.2.17 on 2026-09-11 19:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression (Soft Delete)'), ('RESTORE', 'Restauration'), ('HARD_DELETE', 'Suppression Physique'), ('IMPORT', 'Importation'), ('EXPORT', 'Exportation'), ('LOGIN', 'Connexion')], max_length=20, verbose_name='Action effectuée')),
                ('entity', models.CharField(help_text='Ex: Member, Contact, Profession, Role...', max_length=50, verbose_name='Entité concernée')),
                ('entity_id', models.CharField(help_text='UUID ou clé de l’objet ciblé', max_length=64, verbose_name='Identifiant de l’entité')),
                ('old_values', models.JSONField(blank=True, null=True, verbose_name='Anciennes valeurs')),
                ('new_values', models.JSONField(blank=True, null=True, verbose_name='Nouvelles valeurs')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date et heure de l’événement')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Auteur de l’action')),
            ],
            options={
                'verbose_name': 'Journal d’audit',
                'verbose_name_plural': 'Journaux d’audit',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity', 'entity_id'], name='idx_audit_entity_target'), models.Index(fields=['action', 'created_at'], name='idx_audit_action_date')],
            },
        ),
    ]
