# Generated by Django 5.2.17 on 2026-09-13 17:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0003_alter_member_last_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Intitulé du service')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description générale')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre d’affichage')),
            ],
            options={
                'verbose_name': 'Service du catalogue',
                'verbose_name_plural': 'Catalogue des services',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre d’affichage')),
            ],
            options={
                'verbose_name': 'Catégorie de compétence',
                'verbose_name_plural': 'Catégories de compétences',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MemberAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NOT_SPECIFIED', 'Non renseigné'), ('AVAILABLE', 'Disponible'), ('LIMITED', 'Disponibilité partielle'), ('BUSY', 'Très peu disponible'), ('UNAVAILABLE', 'Non disponible actuellement')], default='NOT_SPECIFIED', max_length=20, verbose_name='Statut de disponibilité')),
                ('open_for_mentoring', models.BooleanField(default=False, verbose_name='Ouvert au mentorat d’élèves / étudiants')),
                ('open_for_dahirah_events', models.BooleanField(default=False, verbose_name='Mobilisable pour les événements & Gamou/Ziarra')),
                ('open_for_pro_help', models.BooleanField(default=False, verbose_name='Disponible pour conseil pro entre disciples')),
                ('open_for_volunteer', models.BooleanField(default=False, verbose_name='Prêt pour des missions bénévoles d’intérêt Dahirah')),
                ('weekly_hours_available', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Heures estimées par semaine')),
                ('preferred_contact_method', models.CharField(blank=True, default='Message interne', max_length=50, verbose_name='Méthode de contact préférée')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Précisions de disponibilité')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='members.member', verbose_name='Membre')),
            ],
            options={
                'verbose_name': 'Disponibilité du membre',
                'verbose_name_plural': 'Disponibilités des membres',
            },
        ),
        migrations.CreateModel(
            name='MemberService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='Titre de l’offre')),
                ('description', models.TextField(verbose_name='Détails & Périmètre')),
                ('service_type', models.CharField(choices=[('VOLUNTEER', 'Entraide Communautaire & Bénévolat'), ('DAHIRAH_RATE', 'Prestation Pro (Tarif Préférentiel Dahirah)'), ('STANDARD', 'Prestation Commerciale Standard'), ('MENTORSHIP', 'Mentorat & Partage d’expérience')], default='DAHIRAH_RATE', max_length=20, verbose_name='Modalité d’entraide')),
                ('terms', models.CharField(blank=True, help_text='Ex: Gratuit pour étudiants, remise de 30% sur devis standard', max_length=200, null=True, verbose_name='Conditions ou tarif Dahirah')),
                ('contact_mode', models.CharField(choices=[('INTERNAL_MESSAGE', 'Message interne'), ('WHATSAPP', 'WhatsApp'), ('PHONE', 'Appel téléphonique'), ('OTHER', 'Autre mode convenu')], default='INTERNAL_MESSAGE', help_text='Protège les coordonnées personnelles du membre', max_length=20, verbose_name='Mode de contact privilégié')),
                ('is_active', models.BooleanField(default=True, verbose_name='Offre active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_offered', to='members.member', verbose_name='Membre prestataire / proposant')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_services', to='network.servicecatalog', verbose_name='Type de service')),
            ],
            options={
                'verbose_name': 'Offre de service membre',
                'verbose_name_plural': 'Offres de services membres',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nom de la compétence')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='network.skillcategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['category__display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MemberRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('SPONSOR', 'Parrain / Marraine d’intégration'), ('MENTOR', 'Mentor / Accompagnateur'), ('COLLABORATOR', 'Collaborateur / Associé'), ('FRATERNAL', 'Lien Fraternel / Recommandation')], max_length=20, verbose_name='Nature de la relation')),
                ('status', models.CharField(choices=[('PENDING', 'En attente de validation'), ('APPROVED', 'Validé / Confirmé'), ('REJECTED', 'Refusé')], default='PENDING', max_length=20, verbose_name='Statut de validation')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Validé le')),
                ('notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Note ou contexte')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Déclaré le')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_relations', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
                ('from_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_relations', to='members.member', verbose_name='Membre source')),
                ('to_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_relations', to='members.member', verbose_name='Membre cible')),
            ],
            options={
                'verbose_name': 'Relation inter-membres',
                'verbose_name_plural': 'Relations inter-membres',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('from_member', 'to_member', 'relation_type'), name='unique_member_relation'), models.CheckConstraint(condition=models.Q(('from_member', models.F('to_member')), _negated=True), name='prevent_self_relation')],
            },
        ),
        migrations.CreateModel(
            name='MemberSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('BEGINNER', 'Débutant / Notions'), ('INTERMEDIATE', 'Intermédiaire / Pratiquant'), ('ADVANCED', 'Avancé / Confirmé'), ('EXPERT', 'Expert / Référent')], default='INTERMEDIATE', max_length=20, verbose_name='Niveau de maîtrise')),
                ('years_experience', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Années d’expérience')),
                ('is_verified', models.BooleanField(default=False, help_text='Vérifié par un référent ou administrateur de la Dahirah', verbose_name='Compétence validée administrativement')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Validé le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Déclaré le')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='members.member', verbose_name='Membre')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_skills', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_skills', to='network.skill', verbose_name='Compétence')),
            ],
            options={
                'verbose_name': 'Compétence du membre',
                'verbose_name_plural': 'Compétences des membres',
                'ordering': ['-is_verified', 'skill__name'],
                'constraints': [models.UniqueConstraint(fields=('member', 'skill'), name='unique_member_skill')],
            },
        ),
    ]
