# Generated by Django 5.2.17 on 2026-09-13 19:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_reindex_members_and_add_shaykh'),
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberNeed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('need_type', models.CharField(choices=[('MENTORSHIP', 'Recherche de mentorat'), ('INTERNSHIP', 'Recherche de stage'), ('JOB_SEARCH', 'Recherche d’emploi'), ('PRO_SERVICE', 'Prestation / Artisan de confiance'), ('LEGAL_ADMIN', 'Conseil juridique ou administratif'), ('ACADEMIC', 'Aide scolaire & universitaire'), ('COMMUNITY_AID', 'Entraide fraternelle'), ('OTHER', 'Autre besoin')], default='OTHER', max_length=30, verbose_name='Type de besoin')),
                ('title', models.CharField(max_length=150, verbose_name='Intitulé de la demande')),
                ('description', models.TextField(verbose_name='Détails & Précisions')),
                ('urgency_level', models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'Prioritaire'), ('CRITICAL', 'Urgent')], default='NORMAL', max_length=20, verbose_name='Degré d’urgence')),
                ('status', models.CharField(choices=[('OPEN', 'Ouvert'), ('IN_PROGRESS', 'En cours de traitement'), ('RESOLVED', 'Résolu / Pourvu'), ('EXPIRED', 'Expiré'), ('CANCELLED', 'Annulé')], default='OPEN', max_length=20, verbose_name='Statut')),
                ('visibility_level', models.CharField(choices=[('PUBLIC', 'Visible à tous les membres connectés'), ('INTERNAL', 'Visible uniquement au réseau ciblé'), ('RESTRICTED_ADMIN', 'Confidentiel (Administration uniquement)')], default='PUBLIC', max_length=25, verbose_name='Visibilité')),
                ('is_anonymous', models.BooleanField(default=False, help_text='Masque le nom du membre pour les autres adhérents, mais reste obligatoirement visible aux administrateurs.', verbose_name='Anonymiser auprès des pairs')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Date d’expiration')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de résolution')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needs', to='members.member', verbose_name='Membre demandeur')),
            ],
            options={
                'verbose_name': 'Besoin / Demande d’entraide',
                'verbose_name_plural': 'Besoins / Demandes d’entraide',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'need_type'], name='idx_needs_status_type'), models.Index(fields=['urgency_level'], name='idx_needs_urgency'), models.Index(fields=['expires_at'], name='idx_needs_expires')],
            },
        ),
    ]
