# Generated by Django 5.2.17 on 2026-09-13 23:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_member_options_member_canonical_name_and_more'),
        ('network', '0002_memberneed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPTED', 'Acceptée'), ('DECLINED', 'Déclinée'), ('CANCELLED', 'Annulée')], db_index=True, default='PENDING', max_length=20, verbose_name='Statut de la demande')),
                ('message', models.TextField(blank=True, default='', verbose_name='Message de présentation ou motivation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse')),
                ('facilitator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilitated_connection_requests', to=settings.AUTH_USER_MODEL, verbose_name='Facilitateur (Admin/Tiers)')),
                ('need', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connection_requests', to='network.memberneed', verbose_name='Besoin associé')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connection_requests', to='members.member', verbose_name='Demandeur')),
                ('resulting_relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_requests', to='network.memberrelation', verbose_name='Relation effective générée')),
                ('target_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connection_requests', to='members.member', verbose_name='Membre sollicité')),
            ],
            options={
                'verbose_name': 'Demande de mise en relation',
                'verbose_name_plural': 'Demandes de mise en relation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='idx_conn_req_status_created')],
                'constraints': [models.CheckConstraint(condition=models.Q(('requester', models.F('target_member')), _negated=True), name='prevent_self_connection_request'), models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'ACCEPTED'])), fields=('need', 'target_member'), name='unique_active_conn_req_need_target'), models.UniqueConstraint(condition=models.Q(('need__isnull', True), ('status__in', ['PENDING', 'ACCEPTED'])), fields=('requester', 'target_member'), name='unique_active_spontaneous_conn_req')],
            },
        ),
    ]
