# Generated by Django 5.2.17 on 2026-09-11 19:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatriculeSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(db_index=True, unique=True, verbose_name='Année')),
                ('last_sequence', models.PositiveIntegerField(default=0, verbose_name='Dernier numéro de séquence')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Séquence Matricule',
                'verbose_name_plural': 'Séquences Matricules',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matricule', models.CharField(db_index=True, help_text='Format concurrent-safe garanti : DM-YYYY-XXXX (ex: DM-2026-0001)', max_length=20, unique=True, verbose_name='Matricule')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Genre')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('situation', models.CharField(choices=[('STUDENT', 'Étudiant'), ('PUPIL', 'Élève'), ('EMPLOYEE', 'Salarié'), ('ENTREPRENEUR', 'Entrepreneur'), ('FREELANCE', 'Indépendant / Freelance'), ('RETIRED', 'Retraité'), ('JOB_SEEKER', 'En recherche d’emploi'), ('OTHER', 'Autre')], default='OTHER', max_length=30, verbose_name='Situation')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/photos/', verbose_name='Photo')),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('INACTIVE', 'Inactif'), ('SUSPENDED', 'Suspendu')], default='ACTIVE', max_length=20, verbose_name='Statut')),
                ('visibility_level', models.CharField(choices=[('PUBLIC', 'Public (Annuaire ouvert)'), ('INTERNAL', 'Interne (Membres connectés uniquement)'), ('RESTRICTED', 'Restreint (Administration uniquement)')], default='INTERNAL', max_length=20, verbose_name='Niveau de visibilité')),
                ('joined_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date d’adhésion')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes internes')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Supprimé (Soft Delete)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profile', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur lié')),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=30, verbose_name='Téléphone')),
                ('whatsapp', models.CharField(blank=True, max_length=30, null=True, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email personnel')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse physique')),
                ('city', models.CharField(default='Dakar', max_length=100, verbose_name='Ville')),
                ('country', models.CharField(default='Sénégal', max_length=100, verbose_name='Pays')),
                ('is_primary', models.BooleanField(default=True, verbose_name='Contact principal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='members.member', verbose_name='Membre')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['last_name', 'first_name'], name='idx_members_names'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['situation'], name='idx_members_situation'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['status', 'is_deleted'], name='idx_members_status_del'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('member',), name='unique_primary_contact_per_member'),
        ),
    ]
