# Generated by Django 5.2.17 on 2026-09-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone_visible_to_members',
            field=models.BooleanField(default=False, help_text='Consentement explicite pour afficher le téléphone aux membres.', verbose_name='Téléphone visible aux membres'),
        ),
    ]
