# Generated by Django 5.2.17 on 2026-09-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_contact_phone_visible_to_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nom'),
        ),
    ]
