# Generated by Django 5.2.17 on 2026-09-13 19:03

import re
from django.db import migrations, models


def migrate_matricules_to_damf(apps, schema_editor):
    Member = apps.get_model('members', 'Member')
    MatriculeSequence = apps.get_model('members', 'MatriculeSequence')

    # 1. Update all members' matricules to DAMF-XXXX
    members = list(Member.objects.all().order_by('matricule'))
    max_seq = 0
    for member in members:
        current = member.matricule or ''
        match = re.search(r'(\d+)$', current)
        if match:
            seq_num = int(match.group(1))
        else:
            max_seq += 1
            seq_num = max_seq

        new_matricule = f"DAMF-{seq_num:04d}"
        if seq_num > max_seq:
            max_seq = seq_num

        member.matricule = new_matricule
        member.save(update_fields=['matricule'])

    # 2. Update / create the MatriculeSequence record for 'DAMF'
    final_seq = max(max_seq, 34) if members else 0
    seq_record = MatriculeSequence.objects.filter(prefix='DAMF').first()
    if seq_record:
        seq_record.last_sequence = final_seq
        seq_record.save(update_fields=['last_sequence'])
    else:
        MatriculeSequence.objects.create(prefix='DAMF', last_sequence=final_seq)


def reverse_matricules(apps, schema_editor):
    Member = apps.get_model('members', 'Member')
    for member in Member.objects.all():
        if member.matricule and member.matricule.startswith('DAMF-'):
            seq = int(member.matricule.split('-')[1])
            member.matricule = f"DAM-2023-{seq:03d}"
            member.save(update_fields=['matricule'])


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriculesequence',
            name='prefix',
            field=models.CharField(default='DAMF', max_length=10, unique=True, verbose_name='Préfixe institutionnel'),
        ),
        migrations.AlterField(
            model_name='matriculesequence',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Année (historique)'),
        ),
        migrations.AlterField(
            model_name='member',
            name='matricule',
            field=models.CharField(db_index=True, help_text='Format concurrent-safe garanti : DAMF-XXXX (ex: DAMF-0001)', max_length=20, unique=True, verbose_name='Matricule'),
        ),
        migrations.RunPython(
            migrate_matricules_to_damf,
            reverse_code=reverse_matricules,
        ),
    ]
