# Generated by Django 5.2.17 on 2026-09-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_reindex_members_and_add_shaykh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Téléphone'),
        ),
    ]
