# Generated by Django 5.2.17 on 2026-09-13 23:02

from django.conf import settings
from django.db import migrations, models


def populate_canonical_and_founder(apps, schema_editor):
    import unicodedata
    Member = apps.get_model('members', 'Member')
    for m in Member.objects.all():
        full_name = f"{m.first_name} {m.last_name}".strip()
        norm = ''.join(c for c in unicodedata.normalize('NFD', full_name) if unicodedata.category(c) != 'Mn')
        m.canonical_name = norm.upper()
        if m.matricule == 'DAMF-0001':
            m.is_founder = True
            m.institutional_priority = 1
        else:
            m.is_founder = False
            m.institutional_priority = 100
        m.save(update_fields=['canonical_name', 'is_founder', 'institutional_priority'])


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_contact_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['institutional_priority', 'canonical_name'], 'verbose_name': 'Membre', 'verbose_name_plural': 'Membres'},
        ),
        migrations.AddField(
            model_name='member',
            name='canonical_name',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Nom complet normalisé sans accents pour le tri alphabétique strict A-Z.', max_length=200, verbose_name='Nom canonique de tri'),
        ),
        migrations.AddField(
            model_name='member',
            name='institutional_priority',
            field=models.PositiveSmallIntegerField(db_index=True, default=100, help_text='1 = Guide Spirituel / Fondateur, 100 = Membres ordinaires.', verbose_name='Priorité protocolaire'),
        ),
        migrations.AddField(
            model_name='member',
            name='is_founder',
            field=models.BooleanField(db_index=True, default=False, help_text='Priorité institutionnelle et protocolaire majeure.', verbose_name='Fondateur / Guide Spirituel'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['institutional_priority', 'canonical_name'], name='idx_members_inst_canon'),
        ),
        migrations.RunPython(populate_canonical_and_founder, migrations.RunPython.noop),
    ]
