# Generated by Django 5.2.17 on 2026-09-14 11:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_member_options_member_canonical_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('PROFILE_PHOTO', 'Photo de profil'), ('ACTIVITY_PHOTO', "Photo d'activité"), ('DOCUMENT', 'Document justificatif'), ('EVENT_PHOTO', "Photo d'événement")], default='PROFILE_PHOTO', max_length=30, verbose_name='Type de média')),
                ('file', models.FileField(upload_to='members/media/', verbose_name='Fichier')),
                ('storage_key', models.CharField(blank=True, max_length=255, verbose_name='Clé de stockage objet')),
                ('mime_type', models.CharField(max_length=100, verbose_name='Type MIME')),
                ('size', models.PositiveIntegerField(help_text='Taille physique du fichier en octets (garantie <= 2 Mo pour les photos).', verbose_name='Taille (octets)')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Largeur (px)')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Hauteur (px)')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titre / Légende')),
                ('is_current_profile_photo', models.BooleanField(default=False, verbose_name='Avatar actif')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date d’enregistrement')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='members.member', verbose_name='Membre')),
            ],
            options={
                'verbose_name': 'Média de membre',
                'verbose_name_plural': 'Médias des membres',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current_profile_photo', True), ('media_type', 'PROFILE_PHOTO')), fields=('member',), name='unique_current_profile_photo_per_member')],
            },
        ),
    ]
