# Generated by Django 5.2.17 on 2026-09-14 14:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_membermedia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_president',
            field=models.BooleanField(db_index=True, default=False, help_text='Direction exécutive et organisationnelle de la Dahirah.', verbose_name='Président de la Dahirah'),
        ),
        migrations.AlterField(
            model_name='member',
            name='institutional_priority',
            field=models.PositiveSmallIntegerField(db_index=True, default=100, help_text='1 = Guide Spirituel / Fondateur, 2 = Président de la Dahirah, 100 = Membres ordinaires.', verbose_name='Priorité protocolaire'),
        ),
        migrations.AlterField(
            model_name='membermedia',
            name='file',
            field=models.FileField(upload_to='members/photos/', verbose_name='Fichier'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('is_founder', True)), fields=('is_founder',), name='unique_active_founder_per_dahirah'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('is_president', True)), fields=('is_president',), name='unique_active_president_per_dahirah'),
        ),
    ]
