# Generated by Django 5.2.17 on 2026-09-11 19:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution', models.CharField(help_text='Ex: UCAD, UGB, ESP, CESAG, Université Virtuelle...', max_length=150, verbose_name='Établissement / Université')),
                ('field', models.CharField(help_text='Ex: Droit, Médecine, Génie Industriel, Diplomatie, Géographie...', max_length=150, verbose_name='Domaine / Filière d’études')),
                ('level', models.CharField(choices=[('BAC', 'Baccalauréat'), ('LICENCE_1', 'Licence 1'), ('LICENCE_2', 'Licence 2'), ('LICENCE_3', 'Licence 3'), ('MASTER_1', 'Master 1'), ('MASTER_2', 'Master 2'), ('DOCTORAT', 'Doctorat / Thèse'), ('BTS_DUT', 'BTS / DUT'), ('OTHER', 'Autre cursus / Certificat')], default='LICENCE_3', max_length=30, verbose_name='Niveau d’études')),
                ('diploma', models.CharField(blank=True, max_length=150, null=True, verbose_name='Intitulé du diplôme')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Diplômé / Terminé'), ('ABANDONED', 'Interrompu')], default='IN_PROGRESS', max_length=20, verbose_name='Statut de la formation')),
                ('start_year', models.PositiveSmallIntegerField(verbose_name='Année de début')),
                ('end_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Année de fin (ou prévue)')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='members.member', verbose_name='Membre')),
            ],
            options={
                'verbose_name': 'Formation / Études',
                'verbose_name_plural': 'Formations / Études',
                'ordering': ['-start_year', '-level'],
                'indexes': [models.Index(fields=['field', 'level'], name='idx_edu_field_level')],
            },
        ),
    ]
