# Generated by Django 5.2.17 on 2026-09-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Année de début'),
        ),
    ]
